window.quizConfig.chapters.push({ id: 4, name: "受動態" });

window.quizConfig.questions.push(
    {ch: 4, q: "「〜される」「〜された」という、動作を受ける側の視点に立った文の形を（　）態と言いますか。", a: ["受動態", "受動", "受け身", "じゅどうたい", "うけみ"]},
    {ch: 4, q: "これに対し、通常の「〜する」という能動的な文の形を（　）態と言いますか。", a: ["能動態", "能動", "のうどうたい"]},
    {ch: 4, q: "受動態は「（　）動詞 ＋ 過去分詞」の形で表しますか。動詞の種類を答えなさい。", a: ["be", "be動詞", "ビー動詞"]},
    {ch: 4, q: "受動態の文で「〜によって（動作を行う人）」を表すときに直前に置く前置詞は（　）ですか。英語で答えなさい。", a: ["by", "BY"]},
    {ch: 4, q: "能動態の文の「（　）語」が、受動態の文では主語（S）になりますか。文の要素を漢字で答えなさい。", a: ["目的語", "もくてきご"]},
    {ch: 4, q: "第何文型（SV）の文は目的語がないため、原則として受動態にすることができませんか。数字のみで答えなさい。", a: ["1", "１"]},
    {ch: 4, q: "「Many people love this song.」を受動態にすると、「This song （　） loved by many people.」となります。空欄に入るbe動詞を答えなさい。", a: ["is", "IS"]},
    {ch: 4, q: "「He broke the window.」を受動態にすると、「The window （　） broken by him.」となります。空欄に入るbe動詞を答えなさい。", a: ["was", "WAS"]},
    {ch: 4, q: "「They built these houses in 1990.」を受動態にすると、「These houses （　） built in 1990.」となります。空欄に入るbe動詞を答えなさい。", a: ["were", "WERE"]},
    {ch: 4, q: "受動態の否定文は、（　）動詞の直後に「not」を置きますか。", a: ["be", "be動詞", "ビー動詞"]},
    {ch: 4, q: "受動態の疑問文は、（　）動詞を主語の前に出しますか。", a: ["be", "be動詞", "ビー動詞"]},
    {ch: 4, q: "「この手紙は昨日書かれましたか」を英語にした時、「（　） this letter written yesterday?」の最初に入るbe動詞を答えなさい。", a: ["Was", "was"]},
    {ch: 4, q: "「〜に驚く」を「be surprised （　）」と表すとき、空欄に入る前置詞を答えなさい。", a: ["at", "AT"]},
    {ch: 4, q: "「〜に興味がある」を「be interested （　）」と表すとき、空欄に入る前置詞を答えなさい。", a: ["in", "IN"]},
    {ch: 4, q: "「〜で知られている」を「be known （　）」と表すとき、空欄に入る前置詞を答えなさい。", a: ["for", "FOR"]},
    {ch: 4, q: "「〜に知られている」を「be known （　）」と表すとき、空欄に入る前置詞を答えなさい。", a: ["to", "TO"]},
    {ch: 4, q: "「〜で覆われている」を「be covered （　）」と表すとき、空欄に入る前置詞を答えなさい。", a: ["with", "WITH"]},
    {ch: 4, q: "「〜で満たされている」を「be filled （　）」と表すとき、空欄に入る前置詞を答えなさい。", a: ["with", "WITH"]},
    {ch: 4, q: "「〜に喜ぶ、〜に満足する」を「be pleased （　）」と表すとき、空欄に入る前置詞を答えなさい。", a: ["with", "at", "WITH", "AT"]},
    {ch: 4, q: "「〜にわくわくする、興奮する」を「be excited （　）」と表すとき、空欄に入る前置詞を答えなさい。", a: ["about", "at", "ABOUT", "AT"]},
    {ch: 4, q: "助動詞（canやmustなど）を含む受動態の形は「助動詞 ＋ （　） ＋ 過去分詞」ですか。空欄に入る英単語を答えなさい。", a: ["be", "BE"]},
    {ch: 4, q: "「この問題はすぐに解決されるべきだ」を英語にした時、「This problem must be （　） soon.」の空欄に入るsolveの適切な過去分詞形を答えなさい。", a: ["solved", "SOLVED"]},
    {ch: 4, q: "「〜されているところだ（現在進行形の受動態）」を英語で表すとき、「be ＋ （　） ＋ 過去分詞」になります。空欄に入る英単語を答えなさい。", a: ["being", "BEING"]},
    {ch: 4, q: "「その家は今、建てられているところだ」を英語にした時、「The house is （　） built now.」の空欄に入る英単語を答えなさい。", a: ["being", "BEING"]},
    {ch: 4, q: "「〜されてしまった、〜されたことがある（現在完了形の受動態）」を英語で表すとき、「have（has） ＋ （　） ＋ 過去分詞」になります。空欄に入る英単語を答えなさい。", a: ["been", "BEEN"]},
    {ch: 4, q: "「その手紙はもう送られました」を英語にした時、「The letter has already （　） sent.」の空欄に入る英単語を答えなさい。", a: ["been", "BEEN"]},
    {ch: 4, q: "第4文型（SVOO）の文を受動態にする場合、目的語が2つあるため、原則として最大（　）つの受動態の文を作ることができますか。数字のみで答えなさい。", a: ["2", "２"]},
    {ch: 4, q: "「My father gave me this watch.」を「me（人）」を主語にして受動態にすると、「I was （　） this watch by my father.」になります。空欄に入る単語を答えなさい。", a: ["given", "GIVEN"]},
    {ch: 4, q: "「My father gave me this watch.」を「this watch（物）」を主語にして受動態にすると、「This watch was given （　） me by my father.」になります。空欄に入る前置詞を答えなさい。", a: ["to", "TO"]},
    {ch: 4, q: "「They call the dog Pochi.（第5文型）」を受動態にすると、「The dog is （　） Pochi.」となります。空欄に入るcallの適切な過去分詞形を答えなさい。", a: ["called", "CALLED"]},
    {ch: 4, q: "「The news made me sad.（第5文型）」を受動態にすると、「I was （　） sad by the news.」となります。空欄に入るmakeの適切な過去分詞形を答えなさい。", a: ["made", "MADE"]},
    {ch: 4, q: "群動詞（句動詞）（例：laugh at, speak to）を受動態にするときは、前置詞などのパーツを切り離さずに「1つの（　）」として扱いますか。漢字2文字で答えなさい。", a: ["動詞", "どうし"]},
    {ch: 4, q: "「A car ran over the cat.」を受動態にすると、「The cat was run （　） by a car.」になります。空欄に入る前置詞を答えなさい。", a: ["over", "OVER"]},
    {ch: 4, q: "「They speak to him on the street.」を受動態にすると、「He is spoken （　） on the street.」になります。空欄に入る前置詞を答えなさい。", a: ["to", "TO"]},
    {ch: 4, q: "「Everyone looks up to her.（尊敬する）」を受動態にすると、「She is looked up （　） by everyone.」になります。空欄に入る前置詞を答えなさい。", a: ["to", "TO"]},
    {ch: 4, q: "動作主（by 〜）が一般の人々であるときや、誰だか分からない時、言う必要がない時、受動態の文では「by 〜」を（　）することができます。漢字2文字で答えなさい。", a: ["省略", "しょうりゃく"]},
    {ch: 4, q: "「English is spoken in Canada.」の文で、「by people」は書かれていますか、省略されていますか。「省略されている」または「書かれている」で答えなさい。", a: ["省略されている", "しょうりゃくされている"]},
    {ch: 4, q: "「〜と言われている」という世間の噂を、Itを主語にして「It is （　） that ...」と表します。空欄に入るsayの適切な過去分詞形を答えなさい。", a: ["said", "SAID"]},
    {ch: 4, q: "「It is said that he is rich.」をheを主語にして書き換えると、「He is said （　） be rich.」となります。空欄に入る不定詞を作る語を答えなさい。", a: ["to", "TO"]},
    {ch: 4, q: "「It is believed that ...」の日本語訳は、「〜と（　）られている」ですか。漢字1文字を補いなさい。", a: ["信じ", "しんじ"]},
    {ch: 4, q: "「The mountain is covered with snow.」の日本語訳は「その山は雪で（　）ている」ですか。", a: ["覆われている", "おおわれている"]},
    {ch: 4, q: "「be known as 〜」における前置詞asは、「〜（　）知られている」という意味を表しますか。", a: ["として"]},
    {ch: 4, q: "「He was injured in the car accident.」の「injured」は、どのような状態になったことを表しますか。「（　）を負った」の空欄に入る言葉を漢字2文字で答えなさい。", a: ["怪我", "けが"]},
    {ch: 4, q: "「〜で亡くなる」を受動態の形で「be killed （　）」と表すとき、戦争や事故などの場合はどの前置詞を一般的に使いますか。英語2文字で答えなさい。", a: ["in", "IN"]},
    {ch: 4, q: "「The store is closed on Sundays.」において、「closed」は動詞のどのような形（活用）ですか。", a: ["過去分詞", "かこぶんし", "過去分詞形"]},
    {ch: 4, q: "受動態「be + 過去分詞」において、過去分詞は形容詞と同じように主語の「（　）」を表す働きをすることがあります。漢字2文字で答えなさい。", a: ["状態", "じょうたい"]},
    {ch: 4, q: "「My room is cleaned every day.」の主語「My room」は単数ですか、複数ですか。", a: ["単数", "たんすう"]},
    {ch: 4, q: "「My room is cleaned every day.」のbe動詞「is」は、主語が「My room」で時制が「（　）」だから選ばれていますか。", a: ["現在", "現在形", "げんざい"]},
    {ch: 4, q: "「The dynamic soccer game captured everyone's attention.」という能動態の文を受動態にしたとき、新しく主語になる名詞句は「everyone's （　）」ですか。英語で答えなさい。", a: ["attention", "ATTENTION"]},
    {ch: 4, q: "受動態（受け身）の基本構造は「主語 ＋ be動詞 ＋ （　） ＋ (by〜)」ですか。漢字4文字で答えなさい。", a: ["過去分詞", "かこぶんし"]}
);
